spring.application.name=qa-interview-app
spring.datasource.url=jdbc:h2:mem:qaquiz
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.cache=false
# ==========================
# External integrations
# ==========================
integration.open-trivia.base-url=https://opentdb.com/api.php
integration.stackoverflow.base-url=https://api.stackexchange.com/2.3/questions
integration.stackoverflow.question-answers-url=https://api.stackexchange.com/2.3/questions
integration.stackoverflow.answer-url=https://api.stackexchange.com/2.3/answers
integration.stackoverflow.site=stackoverflow
integration.stackoverflow.page-size=20
integration.stackoverflow.sort=votes
integration.stackoverflow.order=desc
integration.stackoverflow.answer-filter=withbody